### ISSUE TITLE
ots.makeFilter使用组合条件抛出异常

### ISSUE THREAD

**Issue by bbeyes** [ali-sdk/ots2#16]
ots.makeFilter('type == @type1 false OR type == @type2 false', {
        type1: 1,
        type2: 2
});

执行以上代码会抛出异常：
TypeError: $$ is not a function

对lib/filter_runner.js文件做以下修改后正常

<img width="587" alt="code" src="https://cloud.githubusercontent.com/assets/23734797/23540560/ef67dd52-001c-11e7-946b-3825406c7387.png">

**Comment by JacksonTian** [comment]
1. 请给下错误堆栈。
2. 或者发一个PR。

**Comment by JacksonTian** [comment]
```sh
$ npm publish
+ @alicloud/ots2@1.5.3
```
