### ISSUE TITLE
OTS 2015-12-31 版 API 实现求助。

### ISSUE THREAD

**Issue by plusmancn** [ali-sdk/ots2#17]
最近在实现 OTS 2015-12-31 API 版的 [ots.js](https://github.com/im-js/ots.js)
将支持 PlainBuffer 编码，自增主键。

现在是边看官方文档，边手扒 `java sdk` 代码实现，发现文档描述和具体实现存在一些出入。
@JacksonTian 朴大大，能否帮忙联系下 ots 的内部人员，想请教些问题和反馈些实现出入。

**Comment by JacksonTian** [comment]
PlainBuffer 实际上我在内部已经实现过了。但是外部还没公开 我也不能公开。如果其他语言的SDK公开了，我会把代码迁移过来。

**Comment by plusmancn** [comment]
java，c++ 已经公开了，go 在开发中。
沟通下来，ots 的团队的人似乎还不知道，你已经实现 PlainBuffer 了。
