### ISSUE TITLE
PutRow 的时候，必须 $(column) 一下吗?

### ISSUE THREAD

**Issue by yi** [ali-sdk/ots2#20]
我遇到一个奇怪的情况：

1. 使用 putRow ，column 参数 传入一个 plain object ， putRow 成功
2. 使用 putRow,  column 参数 传入 ots.$(plain object) ， putRow 成功

这两次调用在本质上有啥区别吗？是否传入的 column 一定要用 $ 进行转换？

**Comment by JacksonTian** [comment]
自动转换。column 放 plain 对象即可，sdk 会根据值的类型创建对应类型的 Column。

但需要注意的是类型需要自己控制，相比 OTS.createStringColumn('key', 'value') ，自动转换会更易用，但不严格。

**Comment by yi** [comment]
清楚了，非常感谢！
